import Link from 'next/link';
import MarketingPage from '@/components/marketing/MarketingPage';

export const metadata = {
  title: 'Terms of Service · Luna',
  description: 'The agreement between you and Luna.',
};

export default function TermsPage() {
  return (
    <MarketingPage
      eyebrow="Terms of Service"
      title={
        <>
          A simple <span className="italic text-luna-aurora-pink">agreement.</span>
        </>
      }
      subtitle="The plain-language rules of using Luna."
      lastUpdated="January 2025"
    >
      <p className="callout">
        Important: Luna is a wellness companion, not a medical device. She does not
        diagnose, treat, or prescribe. For medical decisions, always consult a qualified
        clinician.
      </p>

      <h2>1. Accepting These Terms</h2>
      <p>
        By creating a Luna account, you agree to these Terms. If you do not agree,
        please do not use Luna. You must be at least 18 years old to use the service.
      </p>

      <h2>2. What Luna Is</h2>
      <p>
        Luna is a personalized wellness companion for women navigating perimenopause and
        menopause. She listens, remembers, and reflects your patterns through
        conversation, check-ins, and gentle forecasts.
      </p>
      <p>Luna uses artificial intelligence to generate responses. She can make mistakes.</p>

      <h2>3. Medical Disclaimer</h2>
      <p>Luna is not intended to:</p>
      <ul>
        <li>Diagnose any condition.</li>
        <li>Treat, cure, or prevent any disease.</li>
        <li>Prescribe or recommend medication.</li>
        <li>Replace consultation with a licensed healthcare provider.</li>
        <li>Provide emergency medical assistance.</li>
      </ul>
      <p>
        If you are experiencing a medical emergency, call your local emergency number
        immediately. In the US, call 911. In a mental health crisis in the US, call or
        text 988.
      </p>

      <h2>4. Subscriptions And Payments</h2>
      <ul>
        <li>Paid plans auto-renew until canceled.</li>
        <li>Cancel anytime from Manage Subscription.</li>
        <li>After cancellation, access continues until the end of your billing period.</li>
        <li>Prices may change with at least 30 days&apos; notice.</li>
      </ul>

      <h2>5. Your Content</h2>
      <p>
        You own what you write and say to Luna. By using the service, you grant us a
        limited license to process your content solely to provide Luna&apos;s features.
      </p>

      <h2>6. AI-Generated Content</h2>
      <p>
        Luna&apos;s responses are generated by AI. They can be imperfect, incomplete, or
        occasionally inaccurate. You are responsible for how you use Luna&apos;s outputs.
      </p>

      <h2>7. Privacy</h2>
      <p>
        Our <Link href="/privacy">Privacy Policy</Link> describes how we handle your data.
      </p>

      <h2>8. Limitation Of Liability</h2>
      <p>
        To the maximum extent permitted by law, Luna and its creators are not liable for
        indirect, incidental, consequential, or punitive damages arising from your use of
        the service.
      </p>

      <h2>9. Contact</h2>
      <p>
        Questions? Write to <a href="mailto:hello@luna.app">hello@luna.app</a>.
      </p>
    </MarketingPage>
  );
}
